name: Test, lint and build check

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --recursive

      - name: Generate Prisma client
        env:
          SCHEMA_DIR: './node_modules/@prisma/client'
        run: |
          pnpm run prisma:generate

      - name: Run eslint
        run: pnpm run lint:check

      - name: Run tests
        run: pnpm run test

  test_banco_build:
    if: github.head_ref != 'develop'
    needs: test_lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx Driver
        id: docker_driver_setup
        uses: docker/setup-buildx-action@v3

      - name: Run docker build
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max